# Site settings
title: rurabe
email: rurabe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: rurabe
github_username:  rurabe
header-img: "img/site-header.jpg"

# Build settings
exclude : ["_resources"]
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Pacific/Honolulu
paginate: 5
